# Generated by Django 5.2.4 on 2025-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_index_country_index_currency_alter_watchlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='Value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='one_year_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
